// <auto-generated />
using System;
using BookSmartBackEndDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookSmartBackEndDatabase.Migrations
{
    [DbContext(typeof(BookSmartContext))]
    [Migration("20250221232614_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Address", b =>
                {
                    b.Property<Guid>("ADDRESS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ADDRESS_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ADDRESS_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("ADDRESS_LINE_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_LINE_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_POSTCODE_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_POSTCODE_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_TOWN_CITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ADDRESS_ID");

                    b.ToTable("ADDRESSES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Business", b =>
                {
                    b.Property<Guid>("BUSINESS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BUSINESS_ADDRESSADDRESS_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BUSINESS_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("BUSINESS_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("BUSINESS_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BUSINESS_SUBEND")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BUSINESS_SUBSTART")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BUSINESS_UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("BUSINESS_ID");

                    b.HasIndex("BUSINESS_ADDRESSADDRESS_ID");

                    b.ToTable("BUSINESSES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Role", b =>
                {
                    b.Property<Guid>("ROLE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ROLE_ROLETYPEID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ROLE_USERID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ROLE_ID");

                    b.HasIndex("ROLE_ROLETYPEID");

                    b.HasIndex("ROLE_USERID");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.RoleType", b =>
                {
                    b.Property<Guid>("ROLETYPE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ROLETYPE_DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ROLETYPE_LOCKED")
                        .HasColumnType("bit");

                    b.Property<string>("ROLETYPE_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ROLETYPE_ID");

                    b.ToTable("ROLETYPES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.User", b =>
                {
                    b.Property<Guid>("USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BUSINESS_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("USER_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("USER_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("USER_EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_FORENAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("USER_LASTLOGIN")
                        .HasColumnType("datetime2");

                    b.Property<bool>("USER_LOCKED")
                        .HasColumnType("bit");

                    b.Property<string>("USER_PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("USER_PASSWORDEXPIRED")
                        .HasColumnType("bit");

                    b.Property<string>("USER_SURNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_TELEPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_TITLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("USER_UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("USER_ID");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Business", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.Address", "BUSINESS_ADDRESS")
                        .WithMany()
                        .HasForeignKey("BUSINESS_ADDRESSADDRESS_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BUSINESS_ADDRESS");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Role", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.RoleType", "ROLE_ROLETYPE")
                        .WithMany()
                        .HasForeignKey("ROLE_ROLETYPEID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookSmartBackEndDatabase.Models.User", "ROLE_USER")
                        .WithMany("USER_ROLES")
                        .HasForeignKey("ROLE_USERID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ROLE_ROLETYPE");

                    b.Navigation("ROLE_USER");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.User", b =>
                {
                    b.Navigation("USER_ROLES");
                });
#pragma warning restore 612, 618
        }
    }
}
