// <auto-generated />
using System;
using BookSmartBackEndDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookSmartBackEndDatabase.Migrations
{
    [DbContext(typeof(BookSmartContext))]
    [Migration("20260221120331_AppointmentScheduleFKs")]
    partial class AppointmentScheduleFKs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Address", b =>
                {
                    b.Property<Guid>("ADDRESS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ADDRESS_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ADDRESS_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("ADDRESS_LINE_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_LINE_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_POSTCODE_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_POSTCODE_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_TOWN_CITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ADDRESS_ID");

                    b.ToTable("ADDRESSES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Appointment", b =>
                {
                    b.Property<Guid>("APPOINTMENT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("APPOINTMENT_CLIENTUSERID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("APPOINTMENT_COMMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("APPOINTMENT_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("APPOINTMENT_DELETED")
                        .HasColumnType("bit");

                    b.Property<DateTime>("APPOINTMENT_ENDDATETIME")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("APPOINTMENT_SCHEDULEID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("APPOINTMENT_SCHEDULEOVERRIDEID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("APPOINTMENT_SERVICEID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("APPOINTMENT_STAFFUSERID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("APPOINTMENT_STARTDATETIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("APPOINTMENT_STATUS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("APPOINTMENT_UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("APPOINTMENT_ID");

                    b.HasIndex("APPOINTMENT_CLIENTUSERID");

                    b.HasIndex("APPOINTMENT_SCHEDULEID");

                    b.HasIndex("APPOINTMENT_SCHEDULEOVERRIDEID");

                    b.HasIndex("APPOINTMENT_SERVICEID");

                    b.HasIndex("APPOINTMENT_STAFFUSERID");

                    b.ToTable("APPOINTMENTS");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Business", b =>
                {
                    b.Property<Guid>("BUSINESS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BUSINESS_ADDRESSADDRESS_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BUSINESS_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("BUSINESS_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("BUSINESS_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BUSINESS_SUBEND")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BUSINESS_SUBSTART")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BUSINESS_UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("BUSINESS_ID");

                    b.HasIndex("BUSINESS_ADDRESSADDRESS_ID");

                    b.ToTable("BUSINESSES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Role", b =>
                {
                    b.Property<Guid>("ROLE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ROLE_ROLETYPEID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ROLE_USERID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ROLE_ID");

                    b.HasIndex("ROLE_ROLETYPEID");

                    b.HasIndex("ROLE_USERID");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.RoleType", b =>
                {
                    b.Property<Guid>("ROLETYPE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ROLETYPE_DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ROLETYPE_LOCKED")
                        .HasColumnType("bit");

                    b.Property<string>("ROLETYPE_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ROLETYPE_ID");

                    b.ToTable("ROLETYPES");

                    b.HasData(
                        new
                        {
                            ROLETYPE_ID = new Guid("257b4011-ae28-4054-9194-c6045ab11c81"),
                            ROLETYPE_DESCRIPTION = "Administrator",
                            ROLETYPE_LOCKED = false,
                            ROLETYPE_NAME = "Admin"
                        },
                        new
                        {
                            ROLETYPE_ID = new Guid("d7d33ce7-1200-4bce-9b7e-1381061e713b"),
                            ROLETYPE_DESCRIPTION = "Staff",
                            ROLETYPE_LOCKED = false,
                            ROLETYPE_NAME = "Staff"
                        },
                        new
                        {
                            ROLETYPE_ID = new Guid("ce92ed6e-69a4-45fd-a5be-40c382cfdff0"),
                            ROLETYPE_DESCRIPTION = "Client",
                            ROLETYPE_LOCKED = false,
                            ROLETYPE_NAME = "Client"
                        });
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Schedule", b =>
                {
                    b.Property<Guid>("SCHEDULE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SCHEDULE_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SCHEDULE_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<int>("SCHEDULE_DAYOFWEEK")
                        .HasColumnType("int");

                    b.Property<bool>("SCHEDULE_DELETED")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("SCHEDULE_ENDTIME")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("SCHEDULE_STARTTIME")
                        .HasColumnType("time");

                    b.Property<DateTime>("SCHEDULE_UPDATED")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SCHEDULE_USERID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SCHEDULE_ID");

                    b.HasIndex("SCHEDULE_USERID");

                    b.ToTable("SCHEDULES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.ScheduleOverride", b =>
                {
                    b.Property<Guid>("SCHEDULEOVERRIDE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SCHEDULEOVERRIDE_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("SCHEDULEOVERRIDE_DATE")
                        .HasColumnType("date");

                    b.Property<bool>("SCHEDULEOVERRIDE_DELETED")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("SCHEDULEOVERRIDE_ENDTIME")
                        .HasColumnType("time");

                    b.Property<bool>("SCHEDULEOVERRIDE_ISAVAILABLE")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("SCHEDULEOVERRIDE_STARTTIME")
                        .HasColumnType("time");

                    b.Property<DateTime>("SCHEDULEOVERRIDE_UPDATED")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SCHEDULEOVERRIDE_USERID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SCHEDULEOVERRIDE_ID");

                    b.HasIndex("SCHEDULEOVERRIDE_USERID");

                    b.ToTable("SCHEDULEOVERRIDES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Service", b =>
                {
                    b.Property<Guid>("SERVICE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SERVICE_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<Guid>("SERVICE_BUSINESSID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SERVICE_CAPACITY")
                        .HasColumnType("int");

                    b.Property<DateTime>("SERVICE_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SERVICE_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("SERVICE_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SERVICE_DURATION")
                        .HasColumnType("int");

                    b.Property<string>("SERVICE_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SERVICE_PRICE")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("SERVICE_UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("SERVICE_ID");

                    b.HasIndex("SERVICE_BUSINESSID");

                    b.ToTable("SERVICES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.ServiceSchedule", b =>
                {
                    b.Property<Guid>("SERVICESCHEDULE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SERVICESCHEDULE_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SERVICESCHEDULE_DELETED")
                        .HasColumnType("bit");

                    b.Property<Guid>("SERVICESCHEDULE_SCHEDULEID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SERVICESCHEDULE_SERVICEID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SERVICESCHEDULE_UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("SERVICESCHEDULE_ID");

                    b.HasIndex("SERVICESCHEDULE_SCHEDULEID");

                    b.HasIndex("SERVICESCHEDULE_SERVICEID");

                    b.ToTable("SERVICESCHEDULES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.ServiceScheduleOverride", b =>
                {
                    b.Property<Guid>("SERVICESCHEDULEOVERRIDE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SERVICESCHEDULEOVERRIDE_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SERVICESCHEDULEOVERRIDE_DELETED")
                        .HasColumnType("bit");

                    b.Property<Guid>("SERVICESCHEDULEOVERRIDE_SCHEDULEOVERRIDEID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SERVICESCHEDULEOVERRIDE_SERVICEID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SERVICESCHEDULEOVERRIDE_UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("SERVICESCHEDULEOVERRIDE_ID");

                    b.HasIndex("SERVICESCHEDULEOVERRIDE_SCHEDULEOVERRIDEID");

                    b.HasIndex("SERVICESCHEDULEOVERRIDE_SERVICEID");

                    b.ToTable("SERVICESCHEDULEOVERRIDES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.User", b =>
                {
                    b.Property<Guid>("USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BUSINESS_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("USER_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("USER_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("USER_EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_FORENAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("USER_LASTLOGIN")
                        .HasColumnType("datetime2");

                    b.Property<bool>("USER_LOCKED")
                        .HasColumnType("bit");

                    b.Property<string>("USER_PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("USER_PASSWORDEXPIRED")
                        .HasColumnType("bit");

                    b.Property<string>("USER_SURNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_TELEPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_TITLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("USER_UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("USER_ID");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Appointment", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.User", "APPOINTMENT_CLIENTUSER")
                        .WithMany()
                        .HasForeignKey("APPOINTMENT_CLIENTUSERID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookSmartBackEndDatabase.Models.Schedule", "APPOINTMENT_SCHEDULE")
                        .WithMany()
                        .HasForeignKey("APPOINTMENT_SCHEDULEID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookSmartBackEndDatabase.Models.ScheduleOverride", "APPOINTMENT_SCHEDULEOVERRIDE")
                        .WithMany()
                        .HasForeignKey("APPOINTMENT_SCHEDULEOVERRIDEID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BookSmartBackEndDatabase.Models.Service", "APPOINTMENT_SERVICE")
                        .WithMany()
                        .HasForeignKey("APPOINTMENT_SERVICEID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookSmartBackEndDatabase.Models.User", "APPOINTMENT_STAFFUSER")
                        .WithMany()
                        .HasForeignKey("APPOINTMENT_STAFFUSERID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("APPOINTMENT_CLIENTUSER");

                    b.Navigation("APPOINTMENT_SCHEDULE");

                    b.Navigation("APPOINTMENT_SCHEDULEOVERRIDE");

                    b.Navigation("APPOINTMENT_SERVICE");

                    b.Navigation("APPOINTMENT_STAFFUSER");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Business", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.Address", "BUSINESS_ADDRESS")
                        .WithMany()
                        .HasForeignKey("BUSINESS_ADDRESSADDRESS_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BUSINESS_ADDRESS");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Role", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.RoleType", "ROLE_ROLETYPE")
                        .WithMany()
                        .HasForeignKey("ROLE_ROLETYPEID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookSmartBackEndDatabase.Models.User", "ROLE_USER")
                        .WithMany("USER_ROLES")
                        .HasForeignKey("ROLE_USERID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ROLE_ROLETYPE");

                    b.Navigation("ROLE_USER");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Schedule", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.User", "SCHEDULE_USER")
                        .WithMany()
                        .HasForeignKey("SCHEDULE_USERID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SCHEDULE_USER");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.ScheduleOverride", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.User", "SCHEDULEOVERRIDE_USER")
                        .WithMany()
                        .HasForeignKey("SCHEDULEOVERRIDE_USERID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SCHEDULEOVERRIDE_USER");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Service", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.Business", "SERVICE_BUSINESS")
                        .WithMany()
                        .HasForeignKey("SERVICE_BUSINESSID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SERVICE_BUSINESS");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.ServiceSchedule", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.Schedule", "SERVICESCHEDULE_SCHEDULE")
                        .WithMany()
                        .HasForeignKey("SERVICESCHEDULE_SCHEDULEID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookSmartBackEndDatabase.Models.Service", "SERVICESCHEDULE_SERVICE")
                        .WithMany()
                        .HasForeignKey("SERVICESCHEDULE_SERVICEID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SERVICESCHEDULE_SCHEDULE");

                    b.Navigation("SERVICESCHEDULE_SERVICE");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.ServiceScheduleOverride", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.ScheduleOverride", "SERVICESCHEDULEOVERRIDE_SCHEDULEOVERRIDE")
                        .WithMany()
                        .HasForeignKey("SERVICESCHEDULEOVERRIDE_SCHEDULEOVERRIDEID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BookSmartBackEndDatabase.Models.Service", "SERVICESCHEDULEOVERRIDE_SERVICE")
                        .WithMany()
                        .HasForeignKey("SERVICESCHEDULEOVERRIDE_SERVICEID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SERVICESCHEDULEOVERRIDE_SCHEDULEOVERRIDE");

                    b.Navigation("SERVICESCHEDULEOVERRIDE_SERVICE");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.User", b =>
                {
                    b.Navigation("USER_ROLES");
                });
#pragma warning restore 612, 618
        }
    }
}
