// <auto-generated />
using System;
using BookSmartBackEndDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookSmartBackEndDatabase.Migrations
{
    [DbContext(typeof(BookSmartContext))]
    partial class BookSmartContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Address", b =>
                {
                    b.Property<Guid>("ADDRESS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ADDRESS_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ADDRESS_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("ADDRESS_LINE_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_LINE_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_POSTCODE_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_POSTCODE_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_TOWN_CITY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ADDRESS_ID");

                    b.ToTable("ADDRESSES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Business", b =>
                {
                    b.Property<Guid>("BUSINESS_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BUSINESS_ADDRESSADDRESS_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BUSINESS_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("BUSINESS_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("BUSINESS_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BUSINESS_SUBEND")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BUSINESS_SUBSTART")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BUSINESS_UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("BUSINESS_ID");

                    b.HasIndex("BUSINESS_ADDRESSADDRESS_ID");

                    b.ToTable("BUSINESSES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Role", b =>
                {
                    b.Property<Guid>("ROLE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ROLE_ROLETYPEID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ROLE_USERID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ROLE_ID");

                    b.HasIndex("ROLE_ROLETYPEID");

                    b.HasIndex("ROLE_USERID");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.RoleType", b =>
                {
                    b.Property<Guid>("ROLETYPE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ROLETYPE_DESCRIPTION")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ROLETYPE_LOCKED")
                        .HasColumnType("bit");

                    b.Property<string>("ROLETYPE_NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ROLETYPE_ID");

                    b.ToTable("ROLETYPES");

                    b.HasData(
                        new
                        {
                            ROLETYPE_ID = new Guid("257b4011-ae28-4054-9194-c6045ab11c81"),
                            ROLETYPE_DESCRIPTION = "Administrator",
                            ROLETYPE_LOCKED = false,
                            ROLETYPE_NAME = "Admin"
                        },
                        new
                        {
                            ROLETYPE_ID = new Guid("d7d33ce7-1200-4bce-9b7e-1381061e713b"),
                            ROLETYPE_DESCRIPTION = "Staff",
                            ROLETYPE_LOCKED = false,
                            ROLETYPE_NAME = "Staff"
                        },
                        new
                        {
                            ROLETYPE_ID = new Guid("ce92ed6e-69a4-45fd-a5be-40c382cfdff0"),
                            ROLETYPE_DESCRIPTION = "Client",
                            ROLETYPE_LOCKED = false,
                            ROLETYPE_NAME = "Client"
                        });
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.User", b =>
                {
                    b.Property<Guid>("USER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BUSINESS_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("USER_CREATED")
                        .HasColumnType("datetime2");

                    b.Property<bool>("USER_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("USER_EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_FORENAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("USER_LASTLOGIN")
                        .HasColumnType("datetime2");

                    b.Property<bool>("USER_LOCKED")
                        .HasColumnType("bit");

                    b.Property<string>("USER_PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("USER_PASSWORDEXPIRED")
                        .HasColumnType("bit");

                    b.Property<string>("USER_SURNAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_TELEPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_TITLE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("USER_UPDATED")
                        .HasColumnType("datetime2");

                    b.HasKey("USER_ID");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Business", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.Address", "BUSINESS_ADDRESS")
                        .WithMany()
                        .HasForeignKey("BUSINESS_ADDRESSADDRESS_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BUSINESS_ADDRESS");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.Role", b =>
                {
                    b.HasOne("BookSmartBackEndDatabase.Models.RoleType", "ROLE_ROLETYPE")
                        .WithMany()
                        .HasForeignKey("ROLE_ROLETYPEID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookSmartBackEndDatabase.Models.User", "ROLE_USER")
                        .WithMany("USER_ROLES")
                        .HasForeignKey("ROLE_USERID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ROLE_ROLETYPE");

                    b.Navigation("ROLE_USER");
                });

            modelBuilder.Entity("BookSmartBackEndDatabase.Models.User", b =>
                {
                    b.Navigation("USER_ROLES");
                });
#pragma warning restore 612, 618
        }
    }
}
